name: Build Custom Ubuntu ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull Docker image
      run: docker pull ubuntu:latest

    - name: Run custom ISO build script
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ubuntu:latest /bin/bash build_iso.sh
